# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformCredentialsVault < Formula
  desc ""
  homepage "https://github.com/oulman/terraform-credentials-vault"
  version "1.0.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/oulman/terraform-credentials-vault/releases/download/v1.0.6/terraform-credentials-vault_1.0.6_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "20283f3052366c3973f28b49cb900676f3e55ee318a154062770f874b3cab0d2"

      def install
        bin.install "terraform-credentials-vault"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/oulman/terraform-credentials-vault/releases/download/v1.0.6/terraform-credentials-vault_1.0.6_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "3947487f436fc582abc9fd65b1d6b97278141c0fce162c9e6b3b6911c9ff458e"

      def install
        bin.install "terraform-credentials-vault"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oulman/terraform-credentials-vault/releases/download/v1.0.6/terraform-credentials-vault_1.0.6_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "2ab257c86cb89cfe867983c465e38eb657c7eaa75b5333d2b44e31536a1deb34"

      def install
        bin.install "terraform-credentials-vault"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/oulman/terraform-credentials-vault/releases/download/v1.0.6/terraform-credentials-vault_1.0.6_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "bf62594c79c2b94c611ae7b08301f414e8cf3751cf798ff0661cc6a77a26ecd1"

      def install
        bin.install "terraform-credentials-vault"
      end
    end
  end
end
